<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CRM.Domain\CRM.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Xpo" Version="26.1.4" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
  </ItemGroup>

</Project>
